# Generated by Django 3.1.1 on 2020-09-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_category', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_language', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_need', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_p_name', models.CharField(max_length=15)),
                ('_birth_year', models.CharField(max_length=4)),
                ('_death_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_sect', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_status', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=50)),
                ('_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.person')),
                ('_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.category')),
                ('_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.language')),
                ('_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.need')),
                ('_sect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.religion')),
                ('_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.status')),
            ],
        ),
    ]
