# Generated by Django 3.1.1 on 2020-09-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0003_auto_20200923_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_para', models.IntegerField()),
                ('page_chapter', models.IntegerField()),
                ('hadees_verse', models.IntegerField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.book')),
                ('personFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personFor', to='haq.person')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='haq.person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.topic')),
            ],
        ),
    ]
