# Generated by Django 3.1.1 on 2020-09-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0004_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
