# Generated by Django 3.1.1 on 2020-09-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0005_auto_20200924_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='_topic',
            field=models.CharField(max_length=40),
        ),
    ]
