# Generated by Django 3.1.1 on 2020-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0006_auto_20200925_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='_topic',
            field=models.CharField(max_length=50),
        ),
    ]
