# Generated by Django 3.1.1 on 2020-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0007_auto_20200925_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
