# Generated by Django 3.1.1 on 2020-09-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0008_auto_20200925_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='_cat',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='_lang',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='_need',
            new_name='need',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='_sect',
            new_name='sect',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='_status',
            new_name='status',
        ),
    ]
