# Generated by Django 3.1.4 on 2021-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0011_auto_20210312_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
