# Generated by Django 3.1.4 on 2021-03-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0012_auto_20210312_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haq.status'),
        ),
    ]
