# Generated by Django 3.1.4 on 2021-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0013_auto_20210312_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorized_person',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='authorized_person',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='category',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='language',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='language',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='need',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='need',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='reference',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='reference',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='religion',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='religion',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='status',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='status',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='data_status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='topic',
            name='data_user',
            field=models.CharField(default='Admin', max_length=10),
        ),
    ]
