# Generated by Django 3.1.4 on 2021-03-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0016_auto_20210322_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='personFor',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Need',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
