# Generated by Django 3.1.4 on 2021-03-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0017_auto_20210322_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authorized_Person',
        ),
    ]
